services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env

  python:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env
