# Generated by Django 5.1.1 on 2024-10-16 00:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('access_level', models.CharField()),
                ('email', models.CharField()),
                ('image', models.ImageField(upload_to='users/')),
            ],
            options={
                'db_table': 'recognition_user',
            },
        ),
    ]
