# Generated by Django 5.1.1 on 2024-10-15 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='recognition_user',
        ),
    ]
