name: Deploy APS Bio Shield - Backend

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  build-and-push:
    name: "Build and push (Backend)"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate sha
        id: generate_sha
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=${SHA}" >> $GITHUB_OUTPUT

      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKERHUB_REPOSITORY}}:${{ steps.generate_sha.outputs.sha }} -f backend/Dockerfile .

      - name: Say Hello world
        run: echo "Hello world - Backend"

      - name: Log into the container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        run: |
          docker push ${{ secrets.DOCKERHUB_REPOSITORY}}:${{ steps.generate_sha.outputs.sha }}
          docker tag ${{ secrets.DOCKERHUB_REPOSITORY}}:${{ steps.generate_sha.outputs.sha }} ${{ secrets.DOCKERHUB_REPOSITORY}}:latest
          docker push ${{ secrets.DOCKERHUB_REPOSITORY}}:latest

  deploy:
    name: "Deploy to VM"
    needs: build-and-push
    runs-on: self-hosted

    steps:
      - name: Pull image from docker hub
        run: sudo docker pull ${{ secrets.DOCKERHUB_REPOSITORY}}:latest

      - name: Remove docker container
        run: sudo docker rm -f bio-shield

      - name: Run docker container
        run: |
          sudo docker run -d -p 8000:8000
          -e DEBUG=${{ secrets.DEBUG }}
          -e SECRET_KEY=${{ secrets.SECRET_KEY }}
          -e DJANGO_ALLOWED_HOSTS=${{ secrets.DJANGO_ALLOWED_HOSTS }}
          -e POSTGRES_ENGINE=${{ secrets.POSTGRES_ENGINE }}
          -e POSTGRES_DB=${{ secrets.POSTGRES_DB }}
          -e POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          -e POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
          -e POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
          --name bio-shield ${{ secrets.DOCKERHUB_REPOSITORY}}:latest
