name: Deploy APS Bio Shield

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: "Build and push"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate sha
        id: generate_sha
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=${SHA}" >> $GITHUB_OUTPUT

      - name: Say Hello world
        run: echo "Hello world"
